List posts = [
  {
    "userId": "1",
    "username": "Jhon",
    "userImage": "assets/images/profile/cat.jpg",
    "image": "assets/images/post/bridge.jpg",
    "country": "USA",
    "city": "New York",
    "postId": "1",
    "title": "New York",
    "place": "New York",
    "like": "1",
    "comment": "3",
    "press": () {},
  },
  {
    "userId": "2",
    "username": "Alfred",
    "userImage": "assets/images/profile/dog.jpg",
    "image": "assets/images/post/clock.jpg",
    "country": "USA",
    "city": "New York",
    "postId": "2",
    "title": "New York",
    "place": "New York",
    "like": "13",
    "comment": "5",
    "press": () {},
  },
  {
    "userId": "3",
    "username": "Alice",
    "userImage": "assets/images/profile/rabbit.jpg",
    "image": "assets/images/post/florence.jpg",
    "country": "USA",
    "city": "New York",
    "postId": "3",
    "title": "New York",
    "place": "New York",
    "like": "2",
    "comment": "0",
    "press": () {},
  },
  {
    "userId": "1",
    "username": "Jhon",
    "userImage": "assets/images/profile/cat.jpg",
    "image": "assets/images/post/nyc.jpg",
    "country": "USA",
    "city": "New York",
    "postId": "1",
    "title": "New York",
    "place": "New York",
    "like": "1",
    "comment": "3",
    "press": () {},
  },
  {
    "userId": "2",
    "username": "Alfred",
    "userImage": "assets/images/profile/dog.jpg",
    "image": "assets/images/post/sydney.jpg",
    "country": "USA",
    "city": "New York",
    "postId": "2",
    "title": "New York",
    "place": "New York",
    "like": "13",
    "comment": "5",
    "press": () {},
  },
  {
    "userId": "3",
    "username": "Alice",
    "userImage": "assets/images/profile/rabbit.jpg",
    "image": "assets/images/post/windmil.jpg",
    "country": "USA",
    "city": "New York",
    "postId": "3",
    "title": "New York",
    "place": "New York",
    "like": "2",
    "comment": "0",
    "press": () {},
  },
];
